call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'chriskempson/base16-vim'
Plug 'bling/vim-airline'
Plug 'lervag/vimtex', { 'for': 'tex' }
call plug#end()

set tabstop=4
set shiftwidth=4
set softtabstop=0
set expandtab
set smarttab

colorscheme base16-tomorrow
set background=dark
let $NVIM_TUI_ENABLE_TRUE_COLOR=1

set number

let g:airline_powerline_fonts = 1
let g:latex_view_general_viewer = 'zathura'
