call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'chriskempson/vim-tomorrow-theme'
Plug 'bling/vim-airline'
call plug#end()

set tabstop=4
set shiftwidth=4
set softtabstop=0
set expandtab
set smarttab

colorscheme Tomorrow-Night

set number

let g:airline_powerline_fonts = 1
