call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'chriskempson/vim-tomorrow-theme'
call plug#end()

set tabstop=4
set shiftwidth=4
set softtabstop=0
set expandtab
set smarttab

colorscheme Tomorrow-Night

set number
