# environment variables
export EDITOR=/usr/bin/nvim
export TERMINAL=termite
export BROWSER=google-chrome-stable


# load zgen
source "${HOME}/.zgen.zsh"

# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    # prezto options
    zgen prezto editor key-bindings 'vi'
    zgen prezto prompt theme 'pure'
    zgen prezto syntax-highlighting color 'yes'

    # prezto and modules
    zgen prezto
    zgen prezto git
    zgen prezto command-not-found
    zgen prezto syntax-highlighting
    zgen prezto history-substring-search
    zgen prezto fasd

    # save all to init script
    zgen save
fi

# alias definitions
alias v=nvim
alias vv='fasd -f -t -e nvim -B viminfo'
