# environment variables
export EDITOR=/usr/bin/nvim
export TERMINAL=termite
export BROWSER=chromium
export PATH=$HOME/.cargo/bin:$PATH

# Tensorflow
export CUDA_HOME=/opt/cuda
export CUDA_ROOT=$CUDA_HOME
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/cuda/lib64:opt/cuda/extras/CUPTI/lib64"


# load zgen
source "${HOME}/.zgen.zsh"

# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    # prezto options
    zgen prezto editor key-bindings 'vi'
    zgen prezto prompt theme 'pure'
    zgen prezto syntax-highlighting color 'yes'

    # prezto and modules
    zgen prezto
    zgen prezto git
    zgen prezto command-not-found
    zgen prezto syntax-highlighting
    zgen prezto history-substring-search
    zgen prezto fasd

    # save all to init script
    zgen save
fi

# functions
twitch() { livestreamer twitch.tv/"$@" }
santander() { pass show banking/santander | python ~/.santander.py "$@" }

# alias definitions
alias v=nvim
alias vim=nvim
alias python=python3
alias py=python3
alias smi=nvidia-smi
alias vv='fasd -f -t -e nvim -B viminfo'
alias ls='ls --color'
alias pdf='zathura'
